import numpy as np
import matplotlib.pyplot as plt
t = np.fromfile("times.bin", dtype=np.float64)
exact = np.fromfile("exact.bin", dtype=np.float64)
noisy = np.fromfile("noisy.bin", dtype=np.float64)
ckf = np.fromfile("CKF.bin", dtype=np.float64)
srcf = np.fromfile("SRCF.bin", dtype=np.float64)
plt.figure(figsize=(19.2, 10.8))
plt.xlabel("t")
plt.ylabel("x_1")
plt.grid(True, "both")
plt.plot(t, exact[::2])
plt.plot(t, noisy[::2])
plt.plot(t, ckf[::2])
plt.plot(t, srcf[::2])
plt.xlim(t[0], t[-1])
plt.savefig("x_1.svg", dpi=100, bbox_inches="tight")

plt.cla()

plt.figure(figsize=(19.2, 10.8))
plt.xlabel("t")
plt.ylabel("x_2")
plt.grid(True, "both")
plt.plot(t, exact[1::2])
plt.plot(t, noisy[1::2])
plt.plot(t, ckf[1::2])
plt.plot(t, srcf[1::2])
plt.xlim(t[0], t[-1])
plt.savefig("x_2.svg", dpi=100, bbox_inches="tight")